#!/usr/bin/env python3
"""
Generate and compile the register-app shim for hgcc --mpi=mvapich2.
"""

import os
import platform
import subprocess
import sys
import tempfile


def find_main_symbol(objs):
    if platform.system() == "Darwin":
        nm_cmd = ["nm", "-gU"]
    else:
        nm_cmd = ["nm", "-g", "--defined-only"]
    for obj in objs:
        if not obj.endswith(".o") or not os.path.isfile(obj):
            continue
        try:
            out = subprocess.check_output(
                nm_cmd + [obj], stderr=subprocess.DEVNULL).decode(
                    "utf-8", errors="ignore")
        except (OSError, subprocess.CalledProcessError):
            continue
        for line in out.splitlines():
            parts = line.split()
            if not parts:
                continue
            sym = parts[-1]
            if "sst_hg_user_main" in sym:
                if sym.startswith("_"):
                    sym = sym[1:]
                return sym
    return None


def main(argv):
    if "--" not in argv:
        sys.stderr.write(
            "gen_register_shim: missing -- separator before user objects\n")
        return 2
    split = argv.index("--")
    fixed = argv[:split]
    user_objs = argv[split + 1:]
    if len(fixed) != 4 or not user_objs:
        sys.stderr.write(
            "usage: gen_register_shim.py <app_name> <cxx> <inc> <out.o> -- <obj>...\n")
        return 2
    app_name, cxx, inc, out_obj = fixed

    sym = find_main_symbol(user_objs)
    if not sym:
        sys.stderr.write(
            "gen_register_shim: sst_hg_user_main not found in %s\n"
            % ", ".join(user_objs))
        return 1

    tmp_dir = os.path.dirname(os.path.abspath(out_obj)) or os.getcwd()
    fd, shim_cpp = tempfile.mkstemp(
        prefix="hgcc_mv2_shim_", suffix=".cpp", dir=tmp_dir)
    try:
        # userSkeletonMainInitFxn is declared in mercury/common/skeleton.h with
        # C++ linkage; libhg exports the C++-mangled symbol. The user main
        # (sst_hg_user_main_<mangled-path>) is emitted by ssthg_clang as a C
        # symbol, so declare it extern "C". A C++ static initializer (non-const
        # init) runs at DSO load time, matching the original register_app.cpp
        # shim from tests/mv2/.
        with os.fdopen(fd, "w") as fh:
            fh.write(
                "/* auto-generated by hgcc --mpi=mvapich2 for \"%s\" */\n"
                "extern \"C\" int %s(int, char**);\n"
                "typedef int (*main_fxn)(int, char**);\n"
                "extern int userSkeletonMainInitFxn(const char* name, main_fxn fxn);\n"
                "static int _hgcc_mv2_reg =\n"
                "    userSkeletonMainInitFxn(\"%s\", %s);\n"
                % (app_name, sym, app_name, sym))
        cmd = [cxx, "-fPIC", "-std=c++11", "-c", shim_cpp, "-I", inc,
               "-o", out_obj]
        rc = subprocess.call(cmd)
        return rc
    finally:
        try:
            os.remove(shim_cpp)
        except OSError:
            pass


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
